# Generated by Django 4.0 on 2021-12-19 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_comp', models.CharField(max_length=255, verbose_name='Название Компьютера')),
                ('hard_disk_number', models.IntegerField(verbose_name='Количество жестких дисков')),
                ('general_storage', models.IntegerField(verbose_name='Общее количество ГБ ROM')),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_os', models.CharField(max_length=150, verbose_name='Название Операционной системы')),
                ('storage_os', models.IntegerField(verbose_name='Количество занимаемой ОС памяти')),
                ('start_numbers', models.IntegerField(verbose_name='Количество запусков ОС')),
                ('Comp_OS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ComputersOS.computer')),
            ],
        ),
    ]
